### ISSUE TITLE
Video and audio is drifting out of sync

### ISSUE THREAD

**Issue by timkonieczny** [Vanilagy/mediabunny#19]
I'm writing camera and microphone inputs from a `MediaStream` to disk as a webm file using a `StreamTarget`. 

It produces a perfectly playable video, but I noticed that audio and video desynchronizes over time. At the beginning of the video it's aligned, but at the end of a 20min video the delay is quite noticeable.

Here is what my setup looks like. I'm using `mediabunny 1.1.1`.
```ts
const stream = new MediaStream(tracks)

const videoTrack = stream.getVideoTracks()[0]
const audioTrack = stream.getAudioTracks()[0]

const writable = new WritableStream({
    write: chunk => writeChunk(chunk.data, chunk.position) // -> return fileHandle.write(data, 0, data.byteLength, position)
})

const output = new Output({
    format: new WebMOutputFormat(),
    target: new StreamTarget(writable, { chunked: true }),
})

if (videoTrack) {
    const source = new MediaStreamVideoTrackSource(videoTrack, {
        codec: 'vp9',
        bitrate: QUALITY_MEDIUM,
    })
    output.addVideoTrack(source)
}

if (audioTrack) {
    const source = new MediaStreamAudioTrackSource(audioTrack, {
        codec: 'opus',
        bitrate: QUALITY_MEDIUM,
    })
    output.addAudioTrack(source)
}

await initCameraFile() // -> fileHandle = await open(path, "w")

await output.start()

// record some chunks...

await output.finalize()

stream.getTracks().forEach(track => track.stop())

await finalizeCameraFile() // -> return fileHandle?.close()
```

Let me know if you need any more info.

I love the library, would be great to replace my current MediaRecorder with this.

**Comment by Vanilagy** [comment]
Awesome, thank you for reporting this and providing the code. I'll try to reproduce this when I get the chance to. Since it's an over-time drift, I'll probably keep my laptop running for a while, just recording nothing, and then come back after a while to test AV sync. I'll get back to you.

**Comment by Vanilagy** [comment]
Hey, so I recorded a 15 minute video from my webcam and mic, and the audio at the end is just as in-sync as the audio in the beginning. So, I'm unable to reproduce this. Are there any additional infos about your setup that you can share? Or a file, perhaps?

**Comment by timkonieczny** [comment]
Hey, apologies for the late reply!

I did some more testing.
If I just record and save camera / mic from a MediaStream, there don't seem to be any problems with video / audio being out of sync.
My application runs a screen recording with FFMPEG (desktop duplication + hw encoding) in parallel to the mediabunny recording. Then the mediabunny recording drifts out of sync. 
I assume both recorders "fight" over resources, leading to the drift.

If I just use a MediaRecorder I can record in-sync files. 

I'm running the recordings in an electron app on Windows 11. 
I understand my setup is quite specific - no worries if it's out of scope for mediabunny, I appreciate you looking into it anyway!

**Comment by Vanilagy** [comment]
Oh, I see. Are you also able to produce in-sync files when using pure Mediabunny? No MediaRecorder, and no FFmpeg?

**Comment by timkonieczny** [comment]
Yes, exactly.

✅Just Mediabunny
✅MediaRecorder + FFmpeg
❌Mediabunny + FFmpeg

I'll let you know if I get any other insights.

**Comment by Vanilagy** [comment]
Likely something that has to do with a slowdown on your end. Not sure if it's a Mediabunny bug. But, if you have anything new, be sure to let me know!

**Comment by timkonieczny** [comment]
I did some more testing and got new insights!

I recorded a few more videos from a `MediaStream` (camera + microphone) and wrote them to a file via `StreamTarget`, like in my original message.
When looking at video track length and audio track length, the audio track length is too short. This is noticeable when playing the video, but also shows when logging like this: 

```
const videoDuration = await videoTrack.computeDuration()
const audioDuration = await audioTrack.computeDuration()
console.log(`Video duration: ${videoDuration}s, Audio duration: ${audioDuration}s`)
```

**Here is the interesting bit: The audio track is only too short with lossy codecs (aac, opus). With lossless codecs (pcm-s16) everything stays in sync.**

Anyway, I just thought I'd share this since I previously always thought the video track is the issue.

**Comment by timkonieczny** [comment]
The out-of-sync audio issue seems to also occur when transcoding an audio track. 
It seems like the problem might be related to the recording issue, but I've created a new one here, which has all the details and an example project: https://github.com/Vanilagy/mediabunny/issues/176

**Comment by Vanilagy** [comment]
Try again with the fix deployed in #176!

**Comment by timkonieczny** [comment]
I tried again with the latest version. Unfortunately, the problem persists.

Not sure if this helps, but while recording, I get these console logs:
`[24836:1114/114411.998:ERROR:media\capture\video\win\video_capture_device_mf_win.cc:2310] Failed to reserve output capture buffer: 1`

Btw, when I just record with `MediaRecorder`, I get these error messages too, but the video is written with audio in sync.

For now, I'll keep my current approach of recording with `MediaRecorder`, and fixing the file by remuxing with `mediabunny`.

**Comment by Vanilagy** [comment]
@timkonieczny That's such a strange error actually, perhaps worth reporting to the browser issue tracker.

Very interesting that the issue persists. I'm still interested in getting to the bottom of this, so, is the repro still to record yourself for a long time? I know I tried this a while ago but was unable to reproduce it. You've also spoken of a setup with FFmpeg which of course, I have no control over. Is that setup necessary to reproduce this issue?

**Comment by timkonieczny** [comment]
Hey, apologies for the late reply!

I'm only able to reproduce this by recording myself for 10+ min, while running a screen recording with FFmpeg from a terminal simultaneously. It's a bit annoying to reproduce but I haven't found a different way. When recording with mediabunny alone, it's fine.

I've tried a few different encoding options with FFmpeg to see if it makes a difference. However, the audio of the mediabunny video is always out of sync at the end (but ok at the start). 
Just to give some context, here is what I've tried:
- HW encoding via MediaFoundation: `ffmpeg -y -r 30 -filter_complex ddagrab=output_fmt=auto,hwdownload,format=bgra -c:v h264_mf -b:v 7.5M screen.mp4`
- HW encoding via Intel QSV: `ffmpeg -y -r 30 -filter_complex ddagrab=output_fmt=auto,hwdownload,format=bgra -c:v h264_qsv -global_quality 10 screen.mp4`
- SW encoding: `ffmpeg -y -r 30 -filter_complex ddagrab=output_fmt=auto,hwdownload,format=bgra -c:v libx264 -crf 25 -preset ultrafast screen.mp4`

Here is how I'm able to reproduce it:
1. Start FFmpeg from a terminal (any of the options above)
2. Start the mediabunny recording (Feel free to use [this implementation](https://github.com/timkonieczny/mediabunny-test), but I don't think it matters)
3. After 10min, say something to test the audio and stop both recordings

The audio should be out of sync at the end of the video. As you suggested, it probably is a slowdown on my end, caused by the FFmpeg recording. The strange thing is just that, despite all its faults, MediaRecorder still produces correct (synchronized) videos.

Btw, my GPU drivers are up-to-date, so this shouldn't be the issue.

**Comment by Vanilagy** [comment]
Oof, this whole set up is kinda complicated man. Not sure when I'll test this, if ever 😂 (no offense of course, but it does consume time).

That said, I *did* actually make a small algorithmic change to the part of the audio encoder that tries to guarantee sync: https://github.com/Vanilagy/mediabunny/commit/5b703a1c783e4e24b446d12e75877cf317c02e34

Try your code again, maybe it's fixed now, who knows.

**Comment by timkonieczny** [comment]
Hey, good news, it's fixed!
I tried with a bunch of different FFmpeg configs (hw / sw encoding etc.), just to make sure, and it always works now.

Thanks for looking into this, I know it's very much an edge case.

**Comment by Vanilagy** [comment]
Lol that's funny! Glad we figured it out in the end :D This holds the record for Mediabunny issue that took the longest to fix
